add HEAD method for dry-run
cometkim/turbocache pull request #4
Opened 2023-01-30 14:21 UTC by jameslounds

As of turbo 1.5.2, the --dry-run option checks the cache for the artefacts.

This PR lets the worker respond to the HEAD http method

2023-01-30 16:08 UTC, cometkim commented
Can you clean up your fomatter's changes?

2023-01-30 16:53 UTC, jameslounds commented
can you provide a prettier/eslint config for me to run against?

2023-01-30 19:37 UTC, jameslounds commented
I've added a `prettierrc` file, and run it against the code.

I've got another branch where I'm using R2 since I have some artefacts larger than 1mb.
Should I open another PR to your main branch, or do you think it's best to have this on another branch?

2023-01-31 07:44 UTC, cometkim commented
No just please change only relevant. you can use "Save without formatting" if you are on VSCode.

2023-01-31 08:24 UTC, jameslounds commented
Consider this as two features then. I’ve added the HEAD method, and initialised prettier. This will avoid this exact issue should anyone else make a PR

2023-01-31 11:04 UTC, cometkim requested changes

2023-01-31 11:04 UTC, cometkim commented on src/worker.ts
> +    case 'HEAD': {
Response to the `HEAD` method shouldn't have the body, only headers

2023-01-31 11:04 UTC, cometkim commented on .prettierrc
> +}
Please remove irrelevant

2023-01-31 11:04 UTC, cometkim commented on src/worker.ts
> +  // prettier-ignore
```suggestion
```

2023-01-31 11:04 UTC, cometkim commented on src/worker.ts
> +      // prettier-ignore
```suggestion
```

2023-01-31 11:04 UTC, cometkim commented on src/worker.ts
> +      // prettier-ignore
```suggestion
```

2023-01-31 11:04 UTC, cometkim commented on src/worker.ts
> +        // prettier-ignore
```suggestion
```

2023-01-31 11:04 UTC, cometkim commented on src/worker.ts
> +// prettier-ignore
```suggestion
```

2023-01-31 11:04 UTC, cometkim commented on src/worker.ts
> +async function putArtifact(hash: string, artifact: ReadableStream,): Promise<Response> {
```suggestion
async function putArtifact(hash: string, artifact: ReadableStream): Promise<Response> {
```

2023-01-31 11:08 UTC, closed without merging